db.host = ""
db.name = ""
db.username = ""
db.password = ""
site.upload_path = "uploads/"
site.installed = ""
site.name = ""
site.email = ""
site.email_signature = 
site.url = ""
site.date_format = "M jS Y"
site.error_reporting = "1"
site.time_format = "H:iA"
site.template = 
site.valid_file_extensions = "pdf,doc,docx,ppt,pptx,pps,ppsx,odt,xls,xlsx,mp3,m4a,ogg,wav,mp4,m4v,mov,wmv,avi,mpg,ogv,3gp,3g2,jpg,jpeg,jpe,jif,jfif,jfi,gif,png,7z,zip,rar"
site.timezone = "Europe/Bucharest"
user.timeout = "31556926"
licence.key = "X780-9WQ4-7T61-7S8P-6X75-Z910"
video.player = "2"
db.components[] = "core"
db.components[] = "message-manager"
licence.checked = "1339066606"
site.facebook.app_id = 
site.facebook.app_secret = 
site.facebook.login = "0"
site.twitter.app_key = 
site.twitter.app_secret = 
site.twitter.login = "0"
extensions.core.logout_url = "/"
extensions.core.login_url = "/"
extensions.core.register_url = "/"
site.htitle = ""
site.hdesc = ""
site.headerc = 
site.footerc = ""
video.submit = "1"
